Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2018-09, with the labels that each got.

#1 Add tnozicka
  OWNERS
Labels: size/XS

#2 CI fixes
  .gitignore
  Dockerfile
  Makefile
  cluster-kube-apiserver-operator.spec
  hack/build-cross.sh
  hack/build-go.sh
  hack/build-images.sh
  hack/build-rpms.sh
  hack/cherry-pick.sh
  hack/import-restrictions.json
  hack/lib/build/images.sh
  hack/move-upstream.sh
  hack/push-release.sh
  hack/test-go.sh
  hack/update-codegen.sh
  hack/update-generated-bindata.sh
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
  hack/verify-gofmt.sh
  hack/verify-govet.sh
  hack/verify-imports.sh
  hack/verify-upstream-commits.sh
  pkg/operator/start_test.go
  pkg/operator/sync_kubapiserver_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XXL

#5 add scheduler manifest
  cmd/cluster-kube-controller-manager-operator/main.go
  cmd/cluster-kube-controller-manager-operator/render/config.go
  cmd/cluster-kube-controller-manager-operator/render/render.go
  manifests/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  manifests/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Labels: approved, lgtm, size/L

#7 render: complete config
  .gitignore
  Dockerfile
  Makefile
  cmd/cluster-kube-controller-manager-operator/render/render.go
  glide.lock
  hack/update-generated-bindata.sh
  hack/verify-gofmt.sh
  manifests/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  manifests/bootkube/config/bootstrap-config-overrides.yaml
  manifests/bootkube/config/config-overrides.yaml
  manifests/bootkube/manifests/configmap-kube-controller-manager-config.yaml
  manifests/bootkube/manifests/kube-controller-manager-daemonset.yaml
  manifests/bootkube/manifests/openshift-kube-controller-manager-ns.yaml
  manifests/v3.11.0/kube-apiserver/defaultconfig.yaml
  manifests/v3.11.0/kube-apiserver/openshift-kube-controller-manager-ns.yaml
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.pb.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.proto
  vendor/github.com/openshift/api/kubecontrolplane/v1/register.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/spf13/cobra/.circleci/config.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completions_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/init.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_test.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs_test.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs_test.go
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs_test.go
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/bytes_test.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/flag_test.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_int_test.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/string_to_string_test.go
Labels: approved, lgtm, size/XXL

#9 do not use scheduler config for now
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Labels: approved, lgtm, size/XS

#12 don't use hostnetwork in daemonset
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/kube-controller-manager-daemonset.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#10 make render produce minimal running config for later customization
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#11 unblock ci
  .travis.yml
Labels: approved, lgtm, size/XS

#13 add fake scheduler and checkpointer to pass bootkube start
  bindata/bootkube/manifests/fake-checkpointer-daemonset.yaml
  bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml
Labels: approved, lgtm, size/M

#14 correct fake manifests for scheduler and checkpointer
  bindata/bootkube/manifests/fake-checkpointer-daemonset.yaml
  bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml
Labels: approved, lgtm, size/XS

#15 fix: kinds for controllermanageroperatorconfig
  manifests/00_clusterkubecontrollermanageroperator_01_config.crd.yaml
  manifests/00_clusterkubecontrollermanageroperator_02_config.yaml
Labels: approved, lgtm, size/XS
