Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2018-12, with the labels that each got.

#95 make static pods node critical priority
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#99 Bump library go to get fixes in fileobserver and more events
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/issue17_test.go
  vendor/github.com/imdario/mergo/issue23_test.go
  vendor/github.com/imdario/mergo/issue33_test.go
  vendor/github.com/imdario/mergo/issue38_test.go
  vendor/github.com/imdario/mergo/issue50_test.go
  vendor/github.com/imdario/mergo/issue52_test.go
  vendor/github.com/imdario/mergo/issue61_test.go
  vendor/github.com/imdario/mergo/issue64_test.go
  vendor/github.com/imdario/mergo/issue66_test.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/merge_appendslice_test.go
  vendor/github.com/imdario/mergo/merge_test.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/mergo_test.go
  vendor/github.com/imdario/mergo/pr80_test.go
  vendor/github.com/imdario/mergo/pr81_test.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/imdario/mergo/testdata/thing.yml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller_test.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper_unsupported.go
Labels: approved, lgtm, size/XXL

#101 update for status
  glide.lock
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/M

#104 fix kube-controller-manager qps
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  glide.lock
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/L

#105 configobervers: add owners
  pkg/operator/configobservation/cloudprovider/OWNERS
  pkg/operator/configobservation/network/OWNERS
Labels: approved, lgtm, size/S

#106 add memory request to kube-controller-manager and operator pod
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#108 fix failing status
  glide.lock
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/issue17_test.go
  vendor/github.com/imdario/mergo/issue23_test.go
  vendor/github.com/imdario/mergo/issue33_test.go
  vendor/github.com/imdario/mergo/issue38_test.go
  vendor/github.com/imdario/mergo/issue50_test.go
  vendor/github.com/imdario/mergo/issue52_test.go
  vendor/github.com/imdario/mergo/issue61_test.go
  vendor/github.com/imdario/mergo/issue64_test.go
  vendor/github.com/imdario/mergo/issue66_test.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/merge_appendslice_test.go
  vendor/github.com/imdario/mergo/merge_test.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/mergo_test.go
  vendor/github.com/imdario/mergo/pr80_test.go
  vendor/github.com/imdario/mergo/pr81_test.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/imdario/mergo/testdata/thing.yml
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
Labels: approved, lgtm, size/XXL

#109 defaultconfig: enable horizontal pod autoscaler
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#111 bring back conditions
  glide.lock
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/issue17_test.go
  vendor/github.com/imdario/mergo/issue23_test.go
  vendor/github.com/imdario/mergo/issue33_test.go
  vendor/github.com/imdario/mergo/issue38_test.go
  vendor/github.com/imdario/mergo/issue50_test.go
  vendor/github.com/imdario/mergo/issue52_test.go
  vendor/github.com/imdario/mergo/issue61_test.go
  vendor/github.com/imdario/mergo/issue64_test.go
  vendor/github.com/imdario/mergo/issue66_test.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/merge_appendslice_test.go
  vendor/github.com/imdario/mergo/merge_test.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/mergo_test.go
  vendor/github.com/imdario/mergo/pr80_test.go
  vendor/github.com/imdario/mergo/pr81_test.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/imdario/mergo/testdata/thing.yml
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd_test.go
Labels: approved, lgtm, size/XXL

#112 Include kube-ca in client-ca bundle
  bindata/bootkube/manifests/configmap-kube-controller-manager-client-ca.yaml
Labels: approved, lgtm, size/XS

#114 add service monitor resources for operator
  manifests/0000_12_cluster-kube-controller-manager-operator_00_namespace.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_02_service.yaml
  manifests/0000_90_cluster-kube-controller-manager-operator_01_prometheusrole.yaml
  manifests/0000_90_cluster-kube-controller-manager-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_cluster-kube-controller-manager-operator_03_servicemonitor.yaml
Labels: approved, lgtm, size/M
