Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2018-11, with the labels that each got.

#69 Remove references to apiserver.
  pkg/apis/kubecontrollermanager/v1alpha1/types.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/XS

#73 phase-3: add missing certs+keys
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#75 Refactor started for staticpod.NewControllers
  glide.lock
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/client-go/examples/build/README.md
  vendor/github.com/openshift/library-go/.travis.yml
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/OWNERS
  vendor/github.com/openshift/library-go/alpha-build-machinery/README.md
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk.help
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.example.mk.help
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk.help
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/build.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/help.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/scripts/update-deps.sh
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/hack/verify-golint.sh
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/manifests/installer-sa.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/deployment/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/deployment/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
Labels: approved, lgtm, size/XXL

#74 render: remove phase 2 by default
  bindata/bootkube/manifests/daemonset-kube-controller-manager.yaml
  bindata/bootkube/manifests/kube-system-configmap-client-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-kube-controller-manager-config.yaml
  bindata/bootkube/manifests/kube-system-secret-cluster-signing-ca.yaml
  bindata/bootkube/manifests/kube-system-secret-kubeconfig.yaml
  bindata/bootkube/manifests/kube-system-secret-service-account-private-key.yaml
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/L

#65 Wire cloud-provider to kube-controller-manager
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#70 Makefile: remove origin-release target
  Makefile
  README.md
  hack/lib/Dockerfile-origin-release
Labels: approved, lgtm, size/M

#81 move render command to pkg/cmd
  cmd/cluster-kube-controller-manager-operator/main.go
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/cmd/render/testdata/auth/kubeconfig
  pkg/cmd/render/testdata/configs/kube-controller-manager-config-overrides.yaml
  pkg/cmd/render/testdata/tls/admin.crt
  pkg/cmd/render/testdata/tls/admin.key
  pkg/cmd/render/testdata/tls/aggregator-ca.crt
  pkg/cmd/render/testdata/tls/aggregator-ca.key
  pkg/cmd/render/testdata/tls/apiserver-proxy.crt
  pkg/cmd/render/testdata/tls/apiserver-proxy.key
  pkg/cmd/render/testdata/tls/apiserver.crt
  pkg/cmd/render/testdata/tls/apiserver.key
  pkg/cmd/render/testdata/tls/cluster-apiserver-ca.crt
  pkg/cmd/render/testdata/tls/cluster-apiserver-ca.key
  pkg/cmd/render/testdata/tls/etcd-client-ca.crt
  pkg/cmd/render/testdata/tls/etcd-client-ca.key
  pkg/cmd/render/testdata/tls/etcd-client.crt
  pkg/cmd/render/testdata/tls/etcd-client.key
  pkg/cmd/render/testdata/tls/kube-ca.crt
  pkg/cmd/render/testdata/tls/kube-ca.key
  pkg/cmd/render/testdata/tls/kubelet.crt
  pkg/cmd/render/testdata/tls/kubelet.key
  pkg/cmd/render/testdata/tls/machine-config-server.crt
  pkg/cmd/render/testdata/tls/machine-config-server.key
  pkg/cmd/render/testdata/tls/openshift-apiserver.crt
  pkg/cmd/render/testdata/tls/openshift-apiserver.key
  pkg/cmd/render/testdata/tls/root-ca.crt
  pkg/cmd/render/testdata/tls/root-ca.key
  pkg/cmd/render/testdata/tls/service-account.key
  pkg/cmd/render/testdata/tls/service-account.pub
  pkg/cmd/render/testdata/tls/service-serving-ca.crt
  pkg/cmd/render/testdata/tls/service-serving-ca.key
Labels: approved, lgtm, size/XS

#82 Add build machinery
  Makefile
  glide.lock
  hack/boilerplate.txt
  hack/deps
  hack/env
  hack/lib/build/archive.sh
  hack/lib/build/binaries.sh
  hack/lib/build/environment.sh
  hack/lib/build/release.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/cleanup.sh
  hack/lib/cmd.sh
  hack/lib/compress.awk
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/test/junit.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/golang.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/update-generated-bindata.sh
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps.mk
Labels: approved, lgtm, size/XXL

#83 move to operator specific namespace
  manifests/0000_12_cluster-kube-controller-manager-operator_00_namespace.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_03_configmap.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_04_clusterrolebinding.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/starter.go
Labels: approved, lgtm, size/S

#78 update operator config observation status
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#87 update library-go for status
  glide.lock
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
Labels: approved, lgtm, size/S

#88 update api and library-go
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  glide.lock
  pkg/apis/kubecontrollermanager/v1alpha1/types.go
  pkg/apis/kubecontrollermanager/v1alpha1/zz_generated.deepcopy.go
  pkg/cmd/render/render_test.go
  pkg/operator/observe_config.go
  pkg/operator/starter.go
  pkg/operator/staticpod_interface.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/test/assets_test.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd_test.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/manifests/installer-sa.yaml
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/installerpod/cmd_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XXL

#89 use generic config observer
  glide.lock
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_networking_test.go
  pkg/operator/observe_config.go
  pkg/operator/starter.go
  pkg/operator/staticpod_interface.go
  vendor/github.com/blang/semver/.gx/lastpubver
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/examples/main.go
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/json_test.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/range_test.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/semver_test.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sort_test.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/blang/semver/sql_test.go
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_default.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_linux.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/sigma/go-inotify/LICENSE
  vendor/github.com/sigma/go-inotify/PATENTS
  vendor/github.com/sigma/go-inotify/README.md
  vendor/github.com/sigma/go-inotify/inotify_linux.go
  vendor/github.com/sigma/go-inotify/inotify_linux_test.go
Labels: approved, lgtm, size/XXL

#90 Use kube-controller-manager as container name for easier debugging
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#92 remove public info configmap
  bindata/v3.11.0/kube-controller-manager/public-info-role.yaml
  bindata/v3.11.0/kube-controller-manager/public-info-rolebinding.yaml
  bindata/v3.11.0/kube-controller-manager/public-info.yaml
  glide.lock
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
Labels: approved, lgtm, size/L

#91 observer: add install config networking.clusterNetworks support
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_networking_test.go
Labels: approved, lgtm, size/L

#97 Shorten config resource name
  bindata/v3.11.0/kube-controller-manager/cm.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S
