Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2018-10, with the labels that each got.

#17 Add soltysh to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#18 update manifest filenames to conform to expected CVO update payload f…
  manifests/0000_12_cluster-kube-controller-manager-operator_00_namespace.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_01_config.crd.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_02_config.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_03_configmap.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_04_clusterrolebinding.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#19 add locking to prevent host port conflicts
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml
  bindata/bootkube/manifests/kube-controller-manager-daemonset.yaml
  cmd/cluster-kube-controller-manager-operator/render/config.go
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/M

#20 fix selinux errors in lock dirs
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/manifests/kube-controller-manager-daemonset.yaml
Labels: approved, lgtm, size/XS

#21 fix indentation in fake scheduler
  bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml
Labels: approved, lgtm, size/XS

#22 fix clusterrolebinding manifest
  manifests/0000_12_cluster-kube-controller-manager-operator_04_clusterrolebinding.yaml
Labels: approved, lgtm, size/S

#23 only install on master nodes
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#24 tolerate any taint
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#25 manifests: fix invalid yaml
  manifests/0000_12_cluster-kube-controller-manager-operator_04_clusterrolebinding.yaml
Labels: approved, lgtm, size/S

#26 remove operator config from payload
  bindata/v3.11.0/kube-apiserver/operator-config.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#27 Move remaining code to controller-manager
  bindata/v3.11.0/kube-controller-manager/cm.yaml
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  bindata/v3.11.0/kube-controller-manager/deployment.yaml
  bindata/v3.11.0/kube-controller-manager/openshift-kube-controller-manager-ns.yaml
  bindata/v3.11.0/kube-controller-manager/operator-config.yaml
  bindata/v3.11.0/kube-controller-manager/public-info-role.yaml
  bindata/v3.11.0/kube-controller-manager/public-info-rolebinding.yaml
  bindata/v3.11.0/kube-controller-manager/public-info.yaml
  bindata/v3.11.0/kube-controller-manager/sa.yaml
  bindata/v3.11.0/kube-controller-manager/svc.yaml
  pkg/apis/kubecontrollermanager/v1alpha1/register.go
  pkg/apis/kubecontrollermanager/v1alpha1/types.go
  pkg/apis/kubecontrollermanager/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/kubecontrollermanager/v1alpha1/fake/fake_kubeapiserveroperatorconfig.go
  pkg/generated/clientset/versioned/typed/kubecontrollermanager/v1alpha1/fake/fake_kubecontrollermanager_client.go
  pkg/generated/clientset/versioned/typed/kubecontrollermanager/v1alpha1/fake/fake_kubecontrollermanageroperatorconfig.go
  pkg/generated/clientset/versioned/typed/kubecontrollermanager/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/kubecontrollermanager/v1alpha1/kubeapiserveroperatorconfig.go
  pkg/generated/clientset/versioned/typed/kubecontrollermanager/v1alpha1/kubecontrollermanager_client.go
  pkg/generated/clientset/versioned/typed/kubecontrollermanager/v1alpha1/kubecontrollermanageroperatorconfig.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/kubecontrollermanager/v1alpha1/interface.go
  pkg/generated/informers/externalversions/kubecontrollermanager/v1alpha1/kubeapiserveroperatorconfig.go
  pkg/generated/informers/externalversions/kubecontrollermanager/v1alpha1/kubecontrollermanageroperatorconfig.go
  pkg/generated/listers/kubecontrollermanager/v1alpha1/expansion_generated.go
  pkg/generated/listers/kubecontrollermanager/v1alpha1/kubeapiserveroperatorconfig.go
  pkg/generated/listers/kubecontrollermanager/v1alpha1/kubecontrollermanageroperatorconfig.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_kubecontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/version/version.go
Labels: approved, lgtm, size/XXL

#29 Add basic yaml linting test
  pkg/test/assets_test.go
Labels: approved, lgtm, size/M

#28 Ensure operator config exists and has the right image when operator start
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#30 fix asset path for defaultconfig in render
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/XS

#31 render: replace flock by disabled port in phase 1
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml
  bindata/bootkube/manifests/kube-controller-manager-daemonset.yaml
  cmd/cluster-kube-controller-manager-operator/render/config.go
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/M

#32 Make sure the namespace is created first
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
Labels: approved, lgtm, size/XS

#33 Remove scheduler manifests
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml
Labels: approved, lgtm, size/M

#34 bump to latest
  glide.lock
  pkg/operator/operator.go
  pkg/operator/sync_kubecontrollermanager_v311_00.go
  vendor/github.com/openshift/api/authorization/OWNERS
  vendor/github.com/openshift/api/config/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/generated.proto
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.pb.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.proto
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/legacyconfig/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/oauth/OWNERS
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.proto
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/osin/v1/generated.pb.go
  vendor/github.com/openshift/api/osin/v1/generated.proto
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/security/OWNERS
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.proto
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/user/OWNERS
  vendor/github.com/openshift/api/webconsole/v1/generated.pb.go
  vendor/github.com/openshift/api/webconsole/v1/generated.proto
  vendor/github.com/openshift/api/webconsole/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
Labels: approved, lgtm, size/XXL

#35 fix wrong image used by render
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/XS

#36 add image references
  manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#40 bindata: rename namespace file
  bindata/v3.11.0/kube-controller-manager/ns.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#44 render: pluralize --config-overrides-file
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/M

#41 render: remove --config-override-file default
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/S

#37 manifests: provide kube-system configs and secrets
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/configmap-client-ca.yaml
  bindata/bootkube/manifests/daemonset-fake-checkpointer-pod.yaml
  bindata/bootkube/manifests/daemonset-kube-controller-manager.yaml
  bindata/bootkube/manifests/kube-system-configmap-client-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-kube-controller-manager-config.yaml
  bindata/bootkube/manifests/kube-system-secret-cluster-signing-ca.yaml
  bindata/bootkube/manifests/kube-system-secret-kubeconfig.yaml
  bindata/bootkube/manifests/kube-system-secret-service-account-private-key.yaml
  bindata/bootkube/manifests/secret-cluster-signing-ca.yaml
  bindata/bootkube/manifests/secret-service-account-private-key.yaml
  bindata/v3.11.0/kube-controller-manager/deployment.yaml
  cmd/cluster-kube-controller-manager-operator/render/render.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#45 render: remove hacky scheduler support
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/S

#49 render: render: move temporary manifests to installer and fix daemonset
  bindata/bootkube/manifests/daemonset-fake-checkpointer-pod.yaml
  bindata/bootkube/manifests/daemonset-kube-controller-manager.yaml
Labels: approved, lgtm, size/M

#50 rename conflicting file
  bindata/bootkube/manifests/configmap-kube-controller-manager-client-ca.yaml
Labels: approved, lgtm, size/XS

#51 Fix kube-controller-manager-config name
  bindata/bootkube/manifests/configmap-kube-controller-manager-config.yaml
  bindata/v3.11.0/kube-controller-manager/cm.yaml
  bindata/v3.11.0/kube-controller-manager/deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#46 render: switch to options/config pattern
  bindata/bootkube/manifests/kube-system-configmap-kube-controller-manager-config.yaml
  cmd/cluster-kube-controller-manager-operator/render/options/config.go
  cmd/cluster-kube-controller-manager-operator/render/options/generic.go
  cmd/cluster-kube-controller-manager-operator/render/options/manifest.go
  cmd/cluster-kube-controller-manager-operator/render/render.go
  pkg/test/assets_test.go
Labels: approved, lgtm, size/L

#52 Fix deployment command name
  bindata/v3.11.0/kube-controller-manager/deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#54 restore kubeconfig asset read
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/S

#57 Makefile: sync with apiserver
  Makefile
Labels: approved, lgtm, size/S

#56 add basic unit tests for render command
  cmd/cluster-kube-controller-manager-operator/main.go
  cmd/cluster-kube-controller-manager-operator/render/options/generic.go
  cmd/cluster-kube-controller-manager-operator/render/render.go
  cmd/cluster-kube-controller-manager-operator/render/render_test.go
  cmd/cluster-kube-controller-manager-operator/render/testdata/auth/kubeconfig
  cmd/cluster-kube-controller-manager-operator/render/testdata/configs/kube-controller-manager-config-overrides.yaml
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/admin.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/admin.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/aggregator-ca.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/aggregator-ca.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/apiserver-proxy.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/apiserver-proxy.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/apiserver.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/apiserver.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/cluster-apiserver-ca.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/cluster-apiserver-ca.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/etcd-client-ca.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/etcd-client-ca.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/etcd-client.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/etcd-client.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/kube-ca.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/kube-ca.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/kubelet.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/kubelet.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/machine-config-server.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/machine-config-server.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/openshift-apiserver.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/openshift-apiserver.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/root-ca.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/root-ca.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/service-account.key
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/service-account.pub
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/service-serving-ca.crt
  cmd/cluster-kube-controller-manager-operator/render/testdata/tls/service-serving-ca.key
Labels: approved, lgtm, size/XL

#59 add clusteroperator status reporting
  manifests/0000_12_cluster-kube-controller-manager-operator_01_config.crd.yaml
  pkg/operator/starter.go
Labels: approved, lgtm, size/M, size/XL

#62 add observedconfig
  pkg/apis/kubecontrollermanager/v1alpha1/types.go
  pkg/apis/kubecontrollermanager/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/sync_kubecontrollermanager_v311_00.go
Labels: approved, lgtm, size/S

#61 add cabundle config observer
  pkg/operator/observe_config.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_kubecontrollermanager_v311_00.go
Labels: approved, lgtm, size/L

#64 render: temporary --disable-phase-2
  cmd/cluster-kube-controller-manager-operator/render/render.go
Labels: approved, lgtm, size/S

#67 bump(*): bring the fixes in installer controller
  glide.lock
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/build.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/build.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/staticpodcontroller/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/staticpodcontroller/installer_controller_test.go
Labels: approved, lgtm, size/XL

#66 fix OPERATOR_IMAGE image pull spec
  manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#68 add namespace to static pod
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS
