Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-01, with the labels that each got.

#117 make the cloud platform detection tolerant of libvirt
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
Labels: approved, lgtm, size/XS

#118 add clusteroperator resource to CVO payload
  manifests/0000_12_kube-controller-manager-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#119 Support "none" cloudprovider
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm, size/M

#120 tighten resource names
  bindata/v3.11.0/kube-controller-manager/operator-config.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  bindata/v3.11.0/kube-controller-manager/sa.yaml
  bindata/v3.11.0/kube-controller-manager/svc.yaml
  manifests/0000_12_kube-controller-manager-operator_02_service.yaml
  manifests/0000_12_kube-controller-manager-operator_03_configmap.yaml
  manifests/0000_12_kube-controller-manager-operator_04_clusterrolebinding.yaml
  manifests/0000_12_kube-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
  manifests/0000_12_kube-controller-manager-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
  pkg/operator/starter.go
  pkg/operator/staticpod_interface.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#123 set cpu request for pod and operator
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#124 explicitly list metrics port as first containerPort
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#122 fix events and extra writes
  glide.lock
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
  pkg/operator/staticpod_interface.go
  pkg/operator/target_config_reconciler_v311_00.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/core_getters.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/fake_informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go.go
Labels: approved, lgtm, size/XXL

#128 use the real service-ca for monitoring
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
  manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
Labels: approved, lgtm, size/XS

#130 support setting loglevel
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#131 Update flexvolume location
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#133 fix bad available status, bad status timestamps, version panic
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile.test
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/openshift/main.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/build.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd_test.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XXL

#134 Static pod revision pruning
  cmd/cluster-kube-controller-manager-operator/main.go
  glide.lock
  pkg/apis/kubecontrollermanager/v1alpha1/types.go
  pkg/apis/kubecontrollermanager/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/operatorclient/operatorclient.go
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/github.com/openshift/library-go/pkg/serviceability/serviceability.go
Labels: approved, lgtm, size/XXL

#140 openstack: Don't observe the openstack CP configs
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
Labels: approved, lgtm, size/XS

#77 add liveness and readiness probes to static pod
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  bindata/v3.11.0/kube-controller-manager/svc.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#143 make serving-cert optional
  pkg/operator/starter.go
Labels: approved, lgtm, size/XS
