Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-08, with the labels that each got.

#274 manifests: fix apiVersion for operator config
  manifests/0000_25_kube-controller-manager-operator_03_configmap.yaml
Labels: approved, lgtm, size/XS

#275 vendor: bump library-go for updated cloudprovider observer
  glide.lock
  vendor/github.com/evanphx/json-patch/go.mod
  vendor/github.com/evanphx/json-patch/go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/testdata/src/a/a.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/types.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/lsp/cache/gofile.go
Labels: approved, lgtm, size/L

#276 bootstrap: log to /var/log/bootstrap-control-plane/kube-controller-manager.log
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
Labels: approved, lgtm, size/S

#278 Move bindata to v4.1.0
  Makefile
  bindata/v4.1.0/kube-controller-manager/cm.yaml
  bindata/v4.1.0/kube-controller-manager/defaultconfig.yaml
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cert-syncer.yaml
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-controller-manager/leader-election-rolebinding.yaml
  bindata/v4.1.0/kube-controller-manager/ns.yaml
  bindata/v4.1.0/kube-controller-manager/pod-cm.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  bindata/v4.1.0/kube-controller-manager/sa.yaml
  bindata/v4.1.0/kube-controller-manager/svc.yaml
  pkg/cmd/render/render.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm, size/L
