Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-12, with the labels that each got.

#315 Bug 1758963: hide secrets in logs
  glide.lock
  glide.yaml
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/github.com/gobuffalo/envy/.env
  vendor/github.com/gobuffalo/envy/test_env/.env
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/change_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/limit_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/scope_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#311 Bug 1744984: Add e2e test for kube controller manager lease configmap deletion
  bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml
  bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#320 Specify "bindNetwork: tcp" so controller manager will work on IPv6 single-stack
  bindata/v4.1.0/kube-controller-manager/default-cluster-policy-controller-config.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#325 Bug 1772756: Inject kube-controller-manager pods trust stores with trusted ca bundle
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  bindata/v4.1.0/kube-controller-manager/trusted-ca-cm.yaml
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
