Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-04, with the labels that each got.

#201 Shorten wait time for the free port
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#205 switch port check to insecure
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#211 Add support for Azure platform
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#209 Add test-e2e make target
  Makefile
  test/e2e/operator_test.go
  test/library/client.go
Labels: approved, lgtm, size/M

#207 switch controller manager to secure port
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#213 specify kubeconfig for delegated authn and authz
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#212 bindata: use default node controller settings
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#206 Sync cloudprovider configmap
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#221 pod.yaml: wire /etc/kubernetes/static-pod-resources/secrets/serving-cert
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#223 show logs in pod status
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#224 explicitly set client-ca and aggregator-client-ca to avoid early fatal contact with unready KAS
  bindata/v3.11.0/kube-controller-manager/kubeconfig-cert-syncer.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  cmd/cluster-kube-controller-manager-operator/main.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#225 remove unused cabundle
  bindata/bootkube/manifests/configmap-initial-kube-controller-manager-csr-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#227 Switch openshift/kcm-o to go1.11
  .travis.yml
Labels: approved, lgtm, size/XS

#220 use cloudprovider observer from library-go
  pkg/operator/configobservation/cloudprovider/OWNERS
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
Labels: approved, lgtm, size/L

#229 upgrade to degraded condition
  glide.lock
  pkg/operator/certrotationcontroller/satokensigner_controller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/gobuffalo/envy/SHOULDERS.md
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/envy_test.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/aggregator.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/zz_generated.openapi.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/generator.go
Labels: approved, lgtm, size/XXL

#230 Use the CVO to create the operator config
  bindata/v3.11.0/kube-controller-manager/operator-config.yaml
  manifests/0000_12_kube-controller-manager-operator_01_operator.cr.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#231 wait for caches to sync
  glide.lock
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/XL

#232 tightens leader election
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm, size/S

#234 update deployment for upgrade and install-gather
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#235 wait for unrevisioned certs
  glide.lock
  pkg/operator/operatorclient/operatorclient.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
  vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/XL

#236 emit events for version changes
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/int32.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/L

#237 Add node-selector annotation to namespace
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-operator-ns.yaml
  bindata/v3.11.0/kube-controller-manager/ns.yaml
  manifests/0000_12_kube-controller-manager-operator_00_namespace.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: size/S

#239 Move component to an appropriate upgrade order (kube cm)
  manifests/0000_25_kube-controller-manager-operator_00_namespace.yaml
  manifests/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  manifests/0000_25_kube-controller-manager-operator_01_operator.cr.yaml
  manifests/0000_25_kube-controller-manager-operator_02_service.yaml
  manifests/0000_25_kube-controller-manager-operator_03_configmap.yaml
  manifests/0000_25_kube-controller-manager-operator_04_clusterrolebinding.yaml
  manifests/0000_25_kube-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#240 change key for cluster-operator version
  glide.lock
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
Labels: approved, lgtm, size/XXL

#242 update for logging and servicemonitor
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
Labels: approved, lgtm, size/M

#241 manifests: bump loglevel of operator to normal
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS
