Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-05, with the labels that each got.

#243 Make installer controller wait for required resources to exists before running installer pod
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/sigs.k8s.io/controller-tools/Gopkg.lock
  vendor/sigs.k8s.io/controller-tools/Gopkg.toml
Labels: approved, lgtm, size/L

#244 Add missing revision suffix when checking for required resources
  glide.lock
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/L

#245 bindata: fix expansion of POD_NAMESPACE in cert-signer
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#249 Update library-go
  glide.lock
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/M

#246 Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/S
