Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-02, with the labels that each got.

#142 tolerate unknown cloud provider
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
Labels: approved, lgtm, size/S

#138 Disable persistent-local-volumes
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#145 Trust cluster-ingress-operator's CA certificate
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#147 fix the csr-signer-ca bundle to keep history
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#150 reduce the sa/ca.crt to avoid trusting every CSR to impersonate the kube-apiserver
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#152 switch to kube-ca as the starting ca.crt
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
Labels: approved, lgtm, size/XS

#154 rotate the kubeconfig for the controller manager
  bindata/bootkube/manifests/secret-kubeconfig.yaml
  bindata/v3.11.0/kube-controller-manager/kubeconfig-cm.yaml
  bindata/v3.11.0/kube-controller-manager/leader-election-rolebinding.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#159 retry configobservation updates
  glide.lock
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_registries.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_registry.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/registry.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/registry.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/registry.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XL

#163 set versions
  glide.lock
  manifests/0000_12_kube-controller-manager-operator_03_version-mapping.yaml
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/coordinates.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/interface.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/resource.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/resources.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XXL

#153 generate our own sa token signer when missing
  bindata/bootkube/manifests/configmap-kube-controller-manager-client-ca.yaml
  bindata/bootkube/manifests/secret-initial-kube-controller-manager-service-account-private-key.yaml
  pkg/operator/certrotationcontroller/satokensigner_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
Labels: approved, do-not-merge/hold, size/L

#166 observe cloud provider from config api
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#167 use new CO condition logic
  glide.lock
  pkg/cmd/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/L

#170 use versionRecorder when writing versions
  pkg/operator/starter.go
Labels: approved, lgtm, size/XS

#168 targetconfigcontroller: emit warning when management state is set to unknown value
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#157 operator: remove openshift prefix from pod name
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#179 add all valid signers to csr-controller-ca
  bindata/bootkube/manifests/configmap-initial-kube-controller-manager-csr-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#176 switch to new discrete certs for sa/ca.crt
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/configmap-initial-kube-controller-manager-serviceaccount-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, size/S

#171 targetconfig: switch pull policy to if not present
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#177 adopt the CSR from the installer
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-operator-ns.yaml
  bindata/bootkube/manifests/secret-csr-signer-signer.yaml
  glide.lock
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/certrotationcontroller/satokensigner_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/XL

#180 bump(*): library-go pickup for rolebinding fix
  glide.lock
  pkg/operator/operatorclient/operatorclient.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/L

#182 set upgradeable condition to false if unsupportedconfigoverride set
  glide.lock
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller_test.go
Labels: approved, lgtm, size/XXL

#181 fix indentation in leader election rolebinding
  bindata/v3.11.0/kube-controller-manager/leader-election-rolebinding.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#183 bump(*): fix installer pod shutdown and rolebinding
  glide.lock
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/golang.org/x/tools/cmd/golsp/main.go
  vendor/golang.org/x/tools/cmd/guru/what.go
Labels: approved, lgtm, size/XL

#184 bump to fix empty status
  glide.lock
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/golang.org/x/tools/go/packages/golist.go
Labels: approved, lgtm, size/L

#185 library-go: fix retry logic when getting installer pod self-reference
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_features.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/wait.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy_test.go
  vendor/golang.org/x/tools/go/analysis/passes/deepequalerrors/deepequalerrors.go
  vendor/golang.org/x/tools/go/analysis/passes/deepequalerrors/deepequalerrors_test.go
  vendor/golang.org/x/tools/go/analysis/passes/deepequalerrors/testdata/src/a/a.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf_test.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/testdata/src/nofmt/nofmt.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/types.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages_test.go
  vendor/golang.org/x/tools/internal/lsp/diagnostics.go
  vendor/golang.org/x/tools/internal/lsp/lsp_test.go
  vendor/golang.org/x/tools/internal/lsp/source/diagnostics.go
Labels: approved, lgtm, size/XL
