Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-06, with the labels that each got.

#257 Bug 1716622: start informers after lister registration
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, lgtm, size/L

#258 monitor kube controller manager
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
  bindata/v3.11.0/kube-controller-manager/ns.yaml
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#259 Switch to go1.12
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#261 only use the new CSR signer after five minute so KAS is up to date
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/M

#260 prevent cert failures when tuning rotation down in CI
  pkg/operator/starter.go
Labels: approved, lgtm, size/XS

#262 bindata/kube-controller-manager: fix cluster-monitoring label
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
  bindata/v3.11.0/kube-controller-manager/ns.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#264 brings back managementState field validation
  manifests/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  manifests/0000_25_kube-controller-manager-operator_01_config.crd.yaml-merge-patch
Labels: approved, lgtm, size/S
