Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-03, with the labels that each got.

#187 bump(library-go): improve logging of what causes a static pod rollout
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
Labels: approved, lgtm, size/S

#188 minor fitting to set versions for our operator
  manifests/0000_12_kube-controller-manager-operator_03_version-mapping.yaml
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
  manifests/0000_12_kube-controller-manager-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/S

#178 feat(targetconfigcontroller): include service-ca bundle in server account CA bundle
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/configobservation/serviceca/observeserviceca.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#190 update service-ca controller namespace
  pkg/cmd/resourcegraph/resourcegraph.go
Labels: approved, lgtm, size/XS

#193 certrotationcontroller: do not fail on unexpected addresses
  pkg/operator/certrotationcontroller/satokensigner_controller.go
Labels: approved, lgtm, size/S

#189 manifests: system-cluster-critical priority for operator
  manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#192 cmd: fix operator component name
  pkg/cmd/operator/cmd.go
Labels: approved, lgtm, size/XS

#195 re-enable local storage
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#196 Remove cluster api dependency
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, size/L

#197 pod.yaml: add init container waiting for free port
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#200 disable kcm secure serving
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
  bindata/v3.11.0/kube-controller-manager/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#204 cloudprovider: add vsphere provider
  pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
Labels: approved, lgtm, size/XS
