Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-09, with the labels that each got.

#279 wire CSR signer to a cert-synced certificates for update
  bindata/v4.1.0/kube-controller-manager/defaultconfig.yaml
  pkg/operator/starter.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm, size/S

#283 Add myself as approver for kcm-o
  OWNERS
Labels: approved, lgtm, size/XS

#282 Fix makefile to allow make images to work
  Dockerfile
  Dockerfile.rhel7
  Makefile
Labels: approved, lgtm, size/S

#285 add non-MITM proxy support
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/M

#289 Update README.md
  README.md
Labels: approved, lgtm, size/L
