Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2019-11, with the labels that each got.

#304 watch for changes to input secrets from the operator namespace
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/M

#301 Bug 1762888: alert when number of expected pods is equal or lower than desired healthy pods in a PDB
  manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#300 Bug 1767047: move rbac for cluster-policy-controller leader lock to kcm-o
  bindata/v4.1.0/kube-controller-manager/leader-election-cluster-policy-controller-role.yaml
  bindata/v4.1.0/kube-controller-manager/leader-election-cluster-policy-controller-rolebinding.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#308 Fix metrics
  manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
  manifests/0000_90_kube-controller-manager-operator_05_alert-kcm-down.yaml
  manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml
  pkg/version/version.go
Labels: approved, lgtm, size/M

#313 pkg,bindata: Update path to cluster-policy-controller service serving certificate and private key
  bindata/v4.1.0/kube-controller-manager/default-cluster-policy-controller-config.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#310 bump(*): library-go for fileobserver fixes
  go.mod
  go.sum
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/gonum/matrix/gendoc.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#312 Add manifest annotations for hosted deployment exclusions
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-controller-manager-operator_05_alert-kcm-down.yaml
  manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml
Labels: approved, lgtm, size/XS

#309 Add namespace to PDB limit alert
  manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml
Labels: approved, lgtm, size/XS

#317 bump(*): library-go to get certsync controller fix
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#318 Bug 1735509: monitoring: move service monitor RBAC rules to manifests/
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#307 Bug 1735509: monitoring: move service monitor RBAC rules to manifests/
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, size/M
