Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2020-04, with the labels that each got.

#383 Bug 1819256: Fix race for localhost-recovery-client-token snapshotting
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#306 Bug 1770303: alert when number of expected pods is equal or lower than desired healthy pods in a PDB
  manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#349 Switch to staticresource control loop
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/M

#384 Add BZ component name to OWNERS
  OWNERS
Labels: approved, lgtm

#385 Bug 1820610: Refresh csr-signer in recovery flow
  pkg/cmd/recoverycontroller/cmd.go
  pkg/cmd/recoverycontroller/csrcontroller.go
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm

#390 Bug 1821689: Fix csr-signer update hotloop
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#389 Bug 1821680: Sync csr-controller-ca to openshift-config-managed namespace
  pkg/cmd/recoverycontroller/cmd.go
  pkg/cmd/recoverycontroller/csrcontroller.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, bugzilla/valid-bug, lgtm

#391 [release-4.4] Bug 1821690: Fix csr-signer update hotloop
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#388 [release-4.4] Bug 1813512: Fix race for localhost-recovery-client-token snapshotting
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#386 [release-4.4] Bug 1820613: Refresh csr-signer in recovery flow
  pkg/cmd/recoverycontroller/cmd.go
  pkg/cmd/recoverycontroller/csrcontroller.go
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#392 Fix CSR signer Secret type
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/modules.txt
Labels: approved, lgtm

#402 Bug 1826259: fix ingress CA cert location
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/test/library/metrics/query.go
  vendor/modules.txt
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#400 Bug 1825983: Sync new client cert-key on recovery
  pkg/cmd/recoverycontroller/csrcontroller.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#394 Bug 1820687: allow patch for updating namespace
  bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
  test/e2e/satokensigner_test.go
  test/library/cluster_operator.go
Labels: approved, bugzilla/valid-bug, lgtm

#404 Bug 1826230: bump(build-machinery-go) and update go-bindata to match
  go.mod
  go.sum
  pkg/dependencymagnet/doc.go
  pkg/operator/v411_00_assets/bindata.go
  vendor/github.com/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/LICENSE
  vendor/github.com/go-bindata/go-bindata/Makefile
  vendor/github.com/go-bindata/go-bindata/README.md
  vendor/github.com/go-bindata/go-bindata/asset.go
  vendor/github.com/go-bindata/go-bindata/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/config.go
  vendor/github.com/go-bindata/go-bindata/convert.go
  vendor/github.com/go-bindata/go-bindata/debug.go
  vendor/github.com/go-bindata/go-bindata/doc.go
  vendor/github.com/go-bindata/go-bindata/file.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/version.go
  vendor/github.com/go-bindata/go-bindata/release.go
  vendor/github.com/go-bindata/go-bindata/restore.go
  vendor/github.com/go-bindata/go-bindata/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/toc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#398 Bug 1828830: add relatedobjects for immediate creation by CVO
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
