Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2020-05, with the labels that each got.

#395 [release-4.3] Bug 1822770: Normalize CPU requests on masters
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#408 Bug 1830364: Updates Resource Graph to use default-ingress-cert CM
  pkg/cmd/resourcegraph/resourcegraph.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#401 [release-4.4] Bug 1825987: Sync new client cert-key on recovery
  pkg/cmd/recoverycontroller/csrcontroller.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#414 Bug 1806640: fix potential errors in Prometheus alerts
  manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#403 Bug 1834852: Add make target to run operator with telepresence
  .gitignore
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#416 Bug 1812126: increase memory and resource limits for installer and pruner pods
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#415 Bug 1821671: Let cloud-provider update services/status on GCP
  bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-binding.yaml
  bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-role.yaml
  pkg/operator/starter.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#411 Bug 1813894: Enable the addition of service ca to token secrets via UnsupportedConfigOverride
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
