Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2020-07, with the labels that each got.

#425 Bug 1835992: Raise operator e2e test timeout
  Makefile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#426 [release-4.4] Bug 1816806: Fix gce cloud provider permissions
  bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-binding.yaml
  bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-role.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#405 Bug: 1805908: Don't use upstream recycler pod
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v4.1.0/config/defaultconfig.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm

#422 [release-4.5] Bug 1851390: Fix port check
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#427 [release-4.3] Bug 1853171: Fix gce cloud provider permissions
  bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-binding.yaml
  bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-role.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#431 use internal LB to avoid outages during kube-apiserver rollout
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/masterurl/observe_masterurl.go
  pkg/operator/configobservation/masterurl/observe_masterurl_test.go
Labels: approved, lgtm
