Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2020-01, with the labels that each got.

#331 Bug 1788148: bump(*): openshift/library-go
  go.mod
  go.sum
  vendor/github.com/openshift/api/.travis.yml
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/glide.lock
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/register.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#323 Bug 1718061: Fix KCM leader election configmap deletion recovery
  bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml
  bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#336 bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#335 Wire certsyncer for localhost recovery
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-controller-manager/localhost-recovery-client-crb.yaml
  bindata/v4.1.0/kube-controller-manager/localhost-recovery-sa.yaml
  bindata/v4.1.0/kube-controller-manager/localhost-recovery-token.yaml
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm, size/L

#324 Bug 1781240: Fix leader election configmap deletion recovery
  bindata/v3.11.0/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml
  bindata/v3.11.0/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#316 Bug 1771809: Add e2e for PodDisruptionBudgetAtLimit alert
  go.mod
  test/e2e/operator_test.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route_client.go
  vendor/github.com/openshift/library-go/test/library/metrics/query.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
