Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2020-03, with the labels that each got.

#356 Bug 1810008: Use the new tls-server-name option in kubeconfig
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cert-syncer.yaml
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  go.mod
  go.sum
  pkg/cmd/recoverycontroller/cmd.go
  pkg/operator/v411_00_assets/bindata.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/overrides.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#358 [release-4.4] Bug 1771410: Use the new tls-server-name option in kubeconfig
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cert-syncer.yaml
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  go.mod
  go.sum
  pkg/cmd/recoverycontroller/cmd.go
  pkg/operator/v411_00_assets/bindata.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/overrides.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#360 Add clusterrole for namespace security allocatoion controller
  bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml
  bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrolebinding.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm, size/L

#359 Bug 1809368: bump openshift/api to remove IPv6DualStack feature flag
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#361 Bug 1810008: Reload client certs
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  pkg/operator/starter.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#362 [release-4.4] Bug 1771410: Reload client certs
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  pkg/operator/starter.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#329 Add basic operator tests
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#370 [release-4.4] Bug 1810182: Remove wildcard COPY form Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#372 [release-4.2] Bug 1810185: Remove wildcard COPY form Dockerfile
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#369 Bug 1810181: Remove wildcard COPY form Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#371 [release-4.3] Bug 1810184: Remove wildcard COPY form Dockerfile
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#374 Bug 1813937: Disable serving for cert regeneration controller to avoid wrong dependency
  pkg/cmd/recoverycontroller/cmd.go
Labels: approved, bugzilla/valid-bug, lgtm

#363 Bug 1812583: Normalize CPU requests on masters
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#378 bump library-go to migrate controllers to factory
  go.mod
  go.sum
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/controller/manager/controller_manager.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#375 [release-4.4] Bug 1813947: Disable serving for cert regeneration controller to avoid wrong dependency
  go.mod
  go.sum
  pkg/cmd/recoverycontroller/cmd.go
  vendor/github.com/gogo/protobuf/gogoproto/gogo.pb.go
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_merge.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/descriptor/descriptor.pb.go
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#380 bootstrap: set log-level 2 instead of 0
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
Labels: approved, lgtm

#373 [release-4.1] Bug 1810186: Remove wildcard COPY form Dockerfile
  Dockerfile
  Dockerfile.rhel7
  Makefile
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#381 Bump to k8s 1.18.0 and library-go,client-go,api rebases
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/k8s.io/api/networking/v1beta1/generated.proto
  vendor/k8s.io/api/networking/v1beta1/types.go
  vendor/k8s.io/api/networking/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: approved, lgtm
