Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2020-09, with the labels that each got.

#440 Bug 1874532: using load balancer, there is no reason to wait on localhost
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#443 bug 1861917: add render --cluster-policy-controller-image to add that controller to bootstrap yaml
  pkg/cmd/render/render.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#441 Bug 1867494: Explicitly use internal LB for KCM and CPC
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/masterurl/observe_masterurl.go
  pkg/operator/configobservation/masterurl/observe_masterurl_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#446 Bug 1861917: Render cluster-policy-controller for bootstrap
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/config/bootstrap-cluster-policy-controller-config-overrides.yaml
  bindata/v4.1.0/config/default-cluster-policy-controller-config.yaml
  pkg/cmd/render/render.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#424 Bug 1851398: Check port availability in the same container
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#447 Bug 1878015: Remove panic on cache sync
  go.mod
  go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/blame.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#449 Bug 1861917: Fix bootstrap cpc
  go.mod
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#448 bug 1874056: add debugging for machine-api, mco, and node teams
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#445 [release-4.5] Bug 1874597: static-pod-installer: remove deadlock by recreating installers that disappear
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#451 Bug 1861917: Enforce cpc config
  pkg/cmd/render/render.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#453 Bug 1861917: Fix bootstrap cpc config file location, certs and RBAC
  bindata/bootkube/config/bootstrap-cluster-policy-controller-config-overrides.yaml
  bindata/bootkube/manifests/00_namespace-security-allocation-controller-clusterrole.yaml
  bindata/bootkube/manifests/00_namespace-security-allocation-controller-clusterrolebinding.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#454 Bug 1881246: squash alerts into a single file
  manifests/0000_90_kube-controller-manager-operator_05_alert-kcm-down.yaml
  manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#456 bug 1871890: add current profile annotations to CVO manifests
  go.sum
  manifests/0000_25_kube-controller-manager-operator_00_namespace.yaml
  manifests/0000_25_kube-controller-manager-operator_01_operator.cr.yaml
  manifests/0000_25_kube-controller-manager-operator_02_service.yaml
  manifests/0000_25_kube-controller-manager-operator_03_configmap.yaml
  manifests/0000_25_kube-controller-manager-operator_04_clusterrolebinding.yaml
  manifests/0000_25_kube-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-controller-manager-operator_01_prometheusrole.yaml
  manifests/0000_90_kube-controller-manager-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
  manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#455 Bug 1881534: Use internal load balancer instead of localhost 4.5
  bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#459 Bug 1883458: add permissions for internal rangeallocation
  bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#460 Bug 1878040: Add validation for logLevel
  go.mod
  go.sum
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
