Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2020-08, with the labels that each got.

#423 [release-4.4] Bug 1851397: Fix port check 4.4
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#434 bump to delay version update until operand updated
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/modules.txt
Labels: approved, lgtm

#438 Bug 1868615: Revert "Don't use upstream recycler pod"
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v4.1.0/config/defaultconfig.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#439 Bug 1858763: bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
