Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2021-02, with the labels that each got.

#500 Bug 1920159: Adjust CPU request for controller manager more precisely
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#503 fixes Developing and debugging the operator section in the readme file.
  README.md
Labels: approved, lgtm

#505 Bug 1911211: Update build-machinery-go to the latest master HEAD
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#506 bug 1844989: Allow to set --tls-cipher-suites and --tls-min-version of KCM instances through observed config
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/listers.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_audit.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
