Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2021-03, with the labels that each got.

#507 bug 1934132: Bump github.com/gogo/protobuf to v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#509 defines test-e2e-preferred-host job for running smoke tests to check if KCM talks to Kube over a preferred host
  Makefile
  test/e2e-preferred-host/kcm_preferred_host_kas_test.go
Labels: approved, lgtm

#508 bug 1924488: Bump github.com/gogo/protobuf to v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
