Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2021-01, with the labels that each got.

#488 Bug 1912888: Add recycler pod template as a ConfigMap
  bindata/v4.1.0/config/defaultconfig.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
  manifests/image-references
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#491 Bug 1887392: bump lib-go to master to pick up authn/z caching
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#492 Bug 1841119: apply extendedArguments directly to kcm in bootstrap
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#493 [release-4.6] Bug 1891742: bump(library-go): controller/staticpod: reduce noise of …
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#494 Bug 1915500: support custom CA bundle for AWS C2S
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#487 Bug 1915473: Annotate manifests for single-node-developer cluster profile
  manifests/0000_25_kube-controller-manager-operator_00_namespace.yaml
  manifests/0000_25_kube-controller-manager-operator_01_operator.cr.yaml
  manifests/0000_25_kube-controller-manager-operator_02_service.yaml
  manifests/0000_25_kube-controller-manager-operator_03_configmap.yaml
  manifests/0000_25_kube-controller-manager-operator_04_clusterrolebinding.yaml
  manifests/0000_25_kube-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-controller-manager-operator_01_prometheusrole.yaml
  manifests/0000_90_kube-controller-manager-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
  manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#497 Bug 1911211: Fix version reporting for recovery-controller
  pkg/cmd/recoverycontroller/cmd.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#499 Extend OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm
