Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2021-11, with the labels that each got.

#569 bump(openshift/api): to get fix for typo in feature gate
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/machine/OWNERS
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machinehealthcheck.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/generated.pb.go
  vendor/github.com/openshift/api/machine/v1beta1/generated.proto
  vendor/github.com/openshift/api/machine/v1beta1/register.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machinehealthcheck.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machineset.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/sharedresource/OWNERS
  vendor/github.com/openshift/api/sharedresource/install.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
  vendor/github.com/openshift/api/sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
  vendor/github.com/openshift/api/sharedresource/v1alpha1/doc.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/register.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/types_shared_configmap.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/types_shared_secret.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#571 bump(*): vendor update
  go.mod
  go.sum
  pkg/operator/certrotationcontroller/satokensigner_controller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/staticpod.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#570 introduce creation of openshift-infra ns and recycler SA
  bindata/assets/kube-controller-manager/namespace-openshift-infra.yaml
  bindata/assets/kube-controller-manager/recycler-sa.yaml
  bindata/bootkube/manifests/0000_00_namespace-openshift-infra.yaml
  pkg/cmd/render/render_test.go
  pkg/operator/starter.go
Labels: approved, lgtm

#573 Bug 2010352: add summary, description and namespace to prometheus alerts
  manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#574 Revert "Merge pull request #554 from atiratree/cpc-metrics"
  bindata/assets/kube-controller-manager/svc-cluster-policy-controller.yaml
  bindata/assets/kube-controller-manager/svc.yaml
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
  pkg/operator/starter.go
Labels: approved, lgtm

#575 update KCM metrics service selector
  bindata/assets/kube-controller-manager/svc.yaml
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
Labels: approved, lgtm

#577 Collect kube-system namespace as a related resource to kube-controller-manager operator
  manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
Labels: approved, lgtm

#578 bug 2026352: Sync with the latest openshift/library-go@master to pick pruner cert dir check
  cmd/cluster-kube-controller-manager-operator/main.go
  go.mod
  go.sum
  pkg/cmd/recoverycontroller/cmd.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
