Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2021-06, with the labels that each got.

#526 Bug 1966126: manifests: drop root_ca_cert_publisher_sync_duration_seconds metric
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#527 Bug 1954790: Use appropriate metric for PDB alerts
  manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#534 Bug 1954790: pdb: Increase PDBAtLimit timeout
  manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#511 Bug 1938636: Set logLevel for policy and recovery controllers
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v411_00_assets/bindata.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#532 Bug 1963730: kube-apiserver failed to load SNI cert and key
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/file_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#535 AUTH-26: CSR Approver manifests
  bindata/v4.1.0/kube-controller-manager/csr_approver_clusterrole.yaml
  bindata/v4.1.0/kube-controller-manager/csr_approver_clusterrolebinding.yaml
  pkg/operator/starter.go
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, lgtm

#539 Update OWNERS
  OWNERS
Labels: approved, lgtm

#540 bump library-go to get context fixes
  go.mod
  go.sum
  pkg/cmd/recoverycontroller/csrcontroller.go
  pkg/operator/certrotationcontroller/satokensigner_controller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/credentialsrequest.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/modules.txt
Labels: approved, lgtm

#538 Bug 1965562: recycler-for-nfs-... does not set requests or priorityClassName
  bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#541 Refactor remaining controllers to factory
  pkg/operator/certrotationcontroller/satokensigner_controller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm
