Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2021-04, with the labels that each got.

#518 Bug 1948431: Bump openshift api version to get CSIMigrationXXX feature gates
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/install.go
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_deprecatedapirequests.yaml
  vendor/github.com/openshift/api/apiserver/v1/doc.go
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_deprecatedapirequest.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/cloudnetwork/OWNERS
  vendor/github.com/openshift/api/cloudnetwork/install.go
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
  vendor/github.com/openshift/api/cloudnetwork/v1/doc.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.pb.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.proto
  vendor/github.com/openshift/api/cloudnetwork/v1/register.go
  vendor/github.com/openshift/api/cloudnetwork/v1/types.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#502 Remove tnozicka from OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#519 Bug 1949418: bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/transport.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#516 Add management workload annotations
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
  bindata/bootkube/manifests/00_openshift-kube-controller-manager-operator-ns.yaml
  bindata/v4.1.0/kube-controller-manager/ns.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
  manifests/0000_25_kube-controller-manager-operator_00_namespace.yaml
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#522 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#523 Bug 1953563: Makefile: add verify-golang-versions
  .ci-operator.yaml
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#521 Rename workload annotations
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/v4.1.0/kube-controller-manager/pod.yaml
  bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
  pkg/operator/v411_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm
