Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2022-01, with the labels that each got.

#568 bug 2005901: Guard controller pdb
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#586 Bug 2035986: Replace deprecated annotation
  bindata/assets/kube-controller-manager/pod.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#587 Bug 2038968: bump(openshift/api): to get CSI migration gates switched off
  go.mod
  go.sum
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml-patch
  vendor/github.com/openshift/api/imageregistry/v1/01_imagepruner.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#588 bug 2005901: Bump library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#589 Bug 2040132: drop --port flag
  bindata/assets/config/defaultconfig.yaml
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#590 Bug 2037856: bump library go
  bindata/assets/config/defaultconfig.yaml
  bindata/assets/kube-controller-manager/leader-election-cluster-policy-controller-role.yaml
  bindata/assets/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml
  go.mod
  go.sum
  pkg/cmd/render/render_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/test/library/metrics/query.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#591 bug 2005901: Sync library go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#593 bug 2044622: Sync with the latest 4.9 library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/missing_san.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#594 Bug 2045872: allow cluster-policy-controller to fallback to default cert
  bindata/assets/kube-controller-manager/svc.yaml
  manifests/0000_25_kube-controller-manager-operator_02_service.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
