Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2022-08, with the labels that each got.

#643 fix TestPodDisruptionBudgetAtLimitAlert by adding SecurityContext to a pod
  test/e2e/operator_test.go
Labels: approved, lgtm

#642 Reset Go mod after openstack library-go bump
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#645 [release-4.10] Bug 2114587: add runbook urls to KCM-o alerts
  manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#649 OCPBUGS-212: gc watcher should close connections after throwing away a client
  pkg/operator/gcwatchercontroller/gcwatcher_controller.go
  pkg/operator/gcwatchercontroller/prometheus_client.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#650 Bug 2118286: always report and reconcile GarbageCollectorDegraded condition
  pkg/operator/gcwatchercontroller/gcwatcher_controller.go
  pkg/operator/gcwatchercontroller/gcwatcher_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
