Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2022-05, with the labels that each got.

#621 Fix debugging information
  README.md
Labels: approved, lgtm

#616 add RBAC for PSa label syncing controller
  bindata/bootkube/manifests/00_podsecurity-admission-label-syncer-controller-clusterrole.yaml
  bindata/bootkube/manifests/00_podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
  pkg/cmd/render/render_test.go
Labels: approved, lgtm

#624 Updating ose-cluster-kube-controller-manager-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm, bugzilla/valid-bug

#626 Bug 2086959: e2e: fix flaky TestLogLevel
  test/e2e/operator_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#628 Bug 2086519: bindata/../namespace-openshift-infra: label namespace as privileged
  bindata/bootkube/manifests/0000_00_namespace-openshift-infra.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent
