Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2023-01, with the labels that each got.

#680 Drop log flags removed in k8s 1.26
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm

#676 OCPBUGS-4478: Sync library go 4.12
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/manifests/secret-csr-signer-signer.yaml
  bindata/bootkube/manifests/secret-initial-kube-controller-manager-service-account-private-key.yaml
  go.mod
  go.sum
  pkg/cmd/render/render.go
  vendor/github.com/openshift/library-go/pkg/assets/assets.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#684 Revert "Drop log flags removed in k8s 1.26"
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm

#681 OCPBUGS-5269: remove unnecessary leader election RBAC
  bindata/assets/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml
  bindata/assets/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#686 honor feature gates during bootstrapping
  bindata/bootkube/config/bootstrap-cluster-policy-controller-config-overrides.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm

#687 [OCPCLOUD-1818] Update library-go dependency to move vSphere to out of tree
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/modules.txt
Labels: do-not-merge/hold

#689 Fixup vendor after library-go update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/modules.txt
Labels: approved, lgtm

#667 OCPBUGS-4304: resources.requests for operator pod
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#690 OCPBUGS-4551: guard controller: set an explicit hostname to avoid name collisions
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
  bindata/bootkube/manifests/secret-csr-signer-signer.yaml
  bindata/bootkube/manifests/secret-initial-kube-controller-manager-service-account-private-key.yaml
  go.mod
  go.sum
  pkg/cmd/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#663 OCPBUGS-3985: Enforce PSA when techpreview is enabled
  go.mod
  go.sum
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  vendor/github.com/openshift/api/config/install.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
  vendor/github.com/openshift/api/config/v1alpha1/Makefile
  vendor/github.com/openshift/api/config/v1alpha1/doc.go
  vendor/github.com/openshift/api/config/v1alpha1/register.go
  vendor/github.com/openshift/api/config/v1alpha1/techpreview.insightsdatagather.testsuite.yaml
  vendor/github.com/openshift/api/config/v1alpha1/types_insights.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
