Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2023-03, with the labels that each got.

#704 OCPBUGS-8235: Guard pod set readiness probe endpoint explicitly 4.10
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#695 [4.12] OCPBUGS-6789: honor feature gates during bootstrapping
  bindata/bootkube/config/bootstrap-cluster-policy-controller-config-overrides.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#712 OCPBUGS-7785: migrate to using lease objects for leader election
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/crypto/keys.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/state/types.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#711 [4.13] OCPBUGS-8710: Move PSa back to logging
  go.mod
  go.sum
  pkg/cmd/render/render_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#714 OWNERS: remove ravi from the owners
  OWNERS
Labels: approved, lgtm

#715 OCPBUGS-10568: migrate to using lease objects for leader election
  bindata/assets/config/defaultconfig.yaml
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#716 OCPBUGS-7785: migrate to using lease objects for leader election
  bindata/assets/config/defaultconfig.yaml
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#706 OCPBUGS-7440: do not degrade KCM when when monitoring stack rollout is in progress
  pkg/operator/gcwatchercontroller/gcwatcher_controller.go
  pkg/operator/gcwatchercontroller/gcwatcher_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
