Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2023-05, with the labels that each got.

#732 Restricted featuregate reader
  go.mod
  go.sum
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/cloud/observe_cloud_volume_plugin.go
  pkg/operator/configobservation/cloud/observe_cloud_volume_plugin_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/generic.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug

#733 Read feature manifest
  go.mod
  go.sum
  pkg/cmd/render/render.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug

#731 [OCPCLOUD-2034] Update cloud provider tests with feature gate changes
  cmd/cluster-kube-controller-manager-operator/main.go
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/cmd/render/testdata/rendered/custom-fg/featuregate-custom.yaml
  pkg/cmd/render/testdata/rendered/default-fg/featuregate.yaml
  pkg/cmd/render/testdata/rendered/duplicate-fg/featuregate-copy.yaml
  pkg/cmd/render/testdata/rendered/duplicate-fg/featuregate.yaml
  pkg/cmd/render/testdata/rendered/mismatched-fg/featuregate-custom.yaml
  pkg/cmd/render/testdata/rendered/mismatched-fg/featuregate.yaml
  pkg/operator/configobservation/cloud/observe_cloud_volume_plugin.go
  pkg/operator/configobservation/cloud/observe_cloud_volume_plugin_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug

#735 Remove featureset flag and use only the manifest
  go.mod
  go.sum
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch
  vendor/github.com/openshift/api/route/v1/stable.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug

#734 [release-4.13] OCPBUGS-11353: AWS should not use external-cloud-volume-plugin post CSI migration
  pkg/operator/configobservation/cloud/observe_cloud_volume_plugin.go
  pkg/operator/configobservation/cloud/observe_cloud_volume_plugin_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#737 OCPBUGS-13579: Drop flags removed in k8s 1.26
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#738 OCPBUGS-13579: remove RBAC for cluster-policy-controller CM leader election
  bindata/assets/kube-controller-manager/leader-election-cluster-policy-controller-role.yaml
  bindata/assets/kube-controller-manager/leader-election-cluster-policy-controller-rolebinding.yaml
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
