Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2023-12, with the labels that each got.

#775 OCPBUGS-25001: Updating ose-cluster-kube-controller-manager-operator-container image to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#757 OCPBUGS-18115: Remove "include.release.openshift.io/ibm-cloud-managed:" annotation
  manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#778 OCPBUGS-5825: Removes legacy cloud-provider resources
  pkg/operator/starter.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#781 TRT-1420: Bump openshift/library-go to pick up revision_controller revert
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#782 NO-JIRA: Make render unit pass consistently
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, jira/valid-reference
