Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2023-09, with the labels that each got.

#746 Bump openshift/* libs
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/pkg/cached/cache.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/k8s.io/kube-openapi/pkg/handler3/handler.go
  vendor/modules.txt
Labels: approved, lgtm, acknowledge-critical-fixes-only

#750 OCPBUGS-16794: installerpod: change pod manifest mode to 0600
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#752 [release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
