Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2024-04, with the labels that each got.

#796 WRKLDS-1071: revision_controller: do not create a new revision when a required object is missing
  go.mod
  go.sum
  test/e2e/satokensigner_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#800 OCPBUGS-31384: use RotatedSigningCASecret and RotatedSelfSignedCertKeySecret only in update mode
  go.mod
  go.sum
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#801 OCPBUGS-31807: use RotatedSigningCASecret and RotatedSelfSignedCertKeySecret only in update mode
  go.mod
  go.sum
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#802 WRKLDS-1169: tolerate node-role.kubernetes.io/control-plane:NoExecute
  manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#804 API-1800: bindata: convert SecretTypeTLS secrets
  bindata/bootkube/manifests/secret-csr-signer-signer.yaml
Labels: approved, lgtm, jira/valid-reference
