Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2025-08, with the labels that each got.

#851 NO-JIRA: targetconfigcontroller: set description for csr-controller-ca
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, jira/valid-reference

#856 RFE-4154: Remove readOnlyRootFilesystem from KCM container
  bindata/assets/kube-controller-manager/pod.yaml
  bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
Labels: approved, lgtm, jira/valid-reference

#854 OCPBUGS-60473: Optimistically update Kube Server and Client CA bundles
  go.mod
  go.sum
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#863 CNTRLPLANE-1275: Add JUnit reporter configuration and README for OTE
  .gitignore
  cmd/cluster-kube-controller-manager-operator-tests-ext/main.go
  go.mod
  test/extended/README.md
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/logging.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/parallel.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/util.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
