Repository openshift/cluster-kube-controller-manager-operator, pull requests merged in 2025-09, with the labels that each got.

#869 CNTRLPLANE-1275:Fixing arch issue
  Makefile
Labels: approved, lgtm, jira/valid-reference, verified

#870 OCPBUGS-61323:CNTRLPLANE-1275:Fixing arch issue
  Makefile
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#861 [release-4.19] OCPBUGS-60682: certrotationcontroller: set RefreshOnlyWhenExpired for CA bundle
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified, verified-later

#862 WRKLDS-1556: Remove --cloud-provider=external from KCM
  bindata/assets/config/defaultconfig.yaml
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, jira/valid-reference, verified

#881 OCPBUGS-62255: Throttle resourcesynccontroller on pairs with dual writers.
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified, verified-later

#882 [release-4.20] OCPBUGS-55217: Throttle resourcesynccontroller on pairs with dual writers.
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified
